[package]
name = "execution-correctness"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
rand = { version = "0.8.3", default-features = false }

consensus-types = { path = "../../consensus/consensus-types", default-features = false }
executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
bcs = "0.1.2"
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-global-constants = { path = "../../config/global-constants"}
diem-logger = { path = "../../crates/diem-logger" }
diem-infallible = { path = "../../crates/diem-infallible" }
diem-secure-net = { path = "../../secure/net" }
diem-secure-storage = { path = "../../secure/storage" }
diem-temppath = { path = "../../crates/diem-temppath" }
diem-types = { path = "../../types" }
diem-vm = { path = "../../diem-move/diem-vm" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
serde = { version = "1.0.124", default-features = false }
storage-client = { path = "../../storage/storage-client" }
storage-interface = { path = "../../storage/storage-interface" }
thiserror = "1.0.24"
# this is actually a dev-dependency (see "Conditional compilation of tests" in coding_guidelines.md)
executor-test-helpers = { path = "../executor-test-helpers", optional = true }

[dev-dependencies]
consensus-types = { path = "../../consensus/consensus-types", default-features = false, features = ["fuzzing"] }
executor-test-helpers = { path = "../executor-test-helpers" }
diem-config = { path = "../../config" , features = ["fuzzing"] }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }

[features]
fuzzing = ["diem-config/fuzzing", "consensus-types/fuzzing"]
