[package]
name = "shuffle"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "CLI frontend for Shuffle"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
directories = "4.0.1"
hex = "0.4.3"
include_dir = { version = "0.6.0", features = ["glob"] }
once_cell = "1.7.2"
rand = "0.8.4"
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde = { version = "1.0.124", features = ["derive"] }
structopt = "0.3.21"
tempfile = "3.2.0"
tokio = { version = "1.8.1", features = ["full"] }
toml = "0.5.8"
url = { version = "2.2.2", features = ["serde"] }

move-abigen = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
diem-api-types = { path = "../../api/types" }
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-genesis-tool = { path = "../../config/management/genesis" }
diem-infallible = { path = "../../crates/diem-infallible"}
diem-json-rpc-types = { path = "../../json-rpc/types" }
diem-node = { path = "../../diem-node" }
diem-sdk = { path = "../../sdk" }
diem-types = { path = "../../types" }
diem-vm = { path = "../../diem-move/diem-vm" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
diemdb = { path = "../../storage/diemdb" }
forge = { path = "../../testsuite/forge" }
generate-key = { path = "../../config/generate-key" }
move-binary-format = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
move-cli = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
move-core-types = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
move-compiler = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
move-package = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
move-unit-test = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
serde-reflection = "0.3.5"
serde-generate = "0.20.6"
serde_json = "1.0.68"
serde_yaml = "0.8.17"
smoke-test = { path = "../../testsuite/smoke-test" }
transaction-builder-generator = { path = "../../diem-move/transaction-builder-generator" }

[[bin]]
name = "shuffle"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3.2.0"

[[test]]
name = "shuffle-forge-integration-tests"
harness = false

[[test]]
name = "shuffle-forge-cli-tests"
harness = false
