[package]
name = "executor-benchmark"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem executor benchmark"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
criterion = "0.3.4"
chrono = "0.4.19"
indicatif = "0.15.0"
itertools = { version = "0.10.0", default-features = false }
jemallocator = { version = "0.3.2", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }
rand = "0.8.3"
rayon = "1.5.0"
serde = "1.0.124"
structopt = "0.3.21"
toml = "0.5.8"

diemdb = { path = "../../storage/diemdb" }
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-infallible = { path = "../../crates/diem-infallible" }
diem-jellyfish-merkle = { path = "../../storage/jellyfish-merkle" }
diem-logger = { path = "../../crates/diem-logger" }
diem-secure-push-metrics = { path = "../../secure/push-metrics" }
diem-types = { path = "../../types" }
diem-vm= { path = "../../diem-move/diem-vm" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
schemadb = { path = "../../storage/schemadb" }
storage-client = { path = "../../storage/storage-client" }
storage-interface = { path = "../../storage/storage-interface" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }

[dev-dependencies]
diem-temppath = { path = "../../crates/diem-temppath" }

[features]
default = []
fuzzing = ["diem-config/fuzzing", "diem-crypto/fuzzing", "diem-types/fuzzing"]

[[bench]]
name = "executor_benchmark"
harness = false
