json_rpc_endpoint: "http://{{ include "diem-validator.fullname" . }}-fullnode:8080"
chain_id: {{ required "chain.chain_id must be set" .Values.chain.chain_id }}
sleep_period_secs: 600
rotation_period_secs: 172800
txn_expiration_secs: 10800

secure_backend:
  type: "vault"
  server: "{{ .Values.vault.server.address }}"
  {{- if .Values.vault.server.ca_cert }}
  ca_certificate: "{{ .Values.vault.server.ca_cert }}"
  {{- end }}
  namespace: "{{ .Values.vault.namespace }}"
  token:
    from_disk: "/opt/vault/token"
