[package]
name = "executor"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem executor"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
fail = "0.4.0"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.7.2"
rayon = "1.5.0"
serde_json = "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }

consensus-types = { path = "../../consensus/consensus-types"}
executor-types = { path = "../executor-types" }
bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto" }
diem-logger = { path = "../../crates/diem-logger" }
diem-metrics = { path = "../../crates/diem-metrics" }
diem-infallible = { path = "../../crates/diem-infallible" }
diem-secure-net = { path = "../../secure/net" }
diem-state-view = { path = "../../storage/state-view" }
diem-types = { path = "../../types" }
move-core-types = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
diem-vm = { path = "../../diem-move/diem-vm" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.3"

diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
executor-test-helpers = { path = "../executor-test-helpers" }
diem-config = { path = "../../config" }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-temppath = { path = "../../crates/diem-temppath" }
diemdb = { path = "../../storage/diemdb" }
move-ir-compiler = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860" }
storage-interface = { path = "../../storage/storage-interface", features=["fuzzing"] }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
vm-genesis = { path = "../../diem-move/vm-genesis" }

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "diem-crypto/fuzzing", "diem-types/fuzzing", "proptest", "storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "diem-vm/failpoints"]
