[package]
name = "diem-rate-limiter"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem implementation for rate limiter"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-infallible = { path= "../../crates/diem-infallible" }
diem-workspace-hack = { version = "0.1", path = "../diem-workspace-hack" }
diem-logger = { path = "../../crates/diem-logger" }
diem-metrics = { path = "../../crates/diem-metrics" }
futures = "0.3.12"
pin-project = "1.0.5"
tokio = { version = "1.8.1", features = ["full"] }
tokio-util = { version = "0.6.4", features = ["compat"] }
