[package]
name = "state-sync-driver"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "The driver for state sync"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.12"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.4"

consensus-notifications = { path = "../../inter-component/consensus-notifications" }
data-streaming-service = { path = "../data-streaming-service" }
diem-config = { path = "../../../config" }
diem-crypto = { path = "../../../crates/diem-crypto" }
diem-data-client = { path = "../../diem-data-client" }
diem-infallible = { path = "../../../crates/diem-infallible" }
diem-logger = { path = "../../../crates/diem-logger" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { version = "0.1", path = "../../../crates/diem-workspace-hack" }
event-notifications = { path = "../../inter-component/event-notifications" }
executor = { path = "../../../execution/executor" }
executor-types = { path = "../../../execution/executor-types" }
mempool-notifications = { path = "../../inter-component/mempool-notifications" }
storage-interface = { path = "../../../storage/storage-interface" }

[dev-dependencies]
claim = "0.5.0"

channel = { path = "../../../crates/channel" }
diemdb = { path = "../../../storage/diemdb" }
diem-crypto = { path = "../../../crates/diem-crypto" }
diem-temppath = { path = "../../../crates/diem-temppath" }
diem-time-service = { path = "../../../crates/diem-time-service", features = ["async", "testing"] }
diem-vm = { path = "../../../diem-move/diem-vm" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
network = { path = "../../../network", features = ["fuzzing"] }
storage-service-client = { path = "../../storage-service/client" }
vm-genesis = { path = "../../../diem-move/vm-genesis", features = ["fuzzing"] }
